"""add llm_calls and outbound_queue tables

Revision ID: 03f18f5deb9e
Revises: 2d1a1cd88393
Create Date: 2026-07-24 16:35:39.308159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '03f18f5deb9e'
down_revision: Union[str, None] = '2d1a1cd88393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column(
        'channel',
        postgresql.ENUM('whatsapp', 'email', name='channel_enum', create_type=False),
        nullable=False,
    ),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tactic_used', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending_approval', 'approved', 'edited', 'rejected', 'sent', name='outbound_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_queue')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit DROP TYPE for the outbound_status_enum it
    # created above; channel_enum is reused by cases/messages, so leave it.
    sa.Enum(name='outbound_status_enum').drop(op.get_bind(), checkfirst=True)
