"""add case plan, escalated, escalation_reason

Revision ID: 2d1a1cd88393
Revises: 73da6bd189ef
Create Date: 2026-07-24 16:24:26.234122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d1a1cd88393'
down_revision: Union[str, None] = '73da6bd189ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        'cases',
        sa.Column('escalated', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('cases', sa.Column('escalation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'escalation_reason')
    op.drop_column('cases', 'escalated')
    op.drop_column('cases', 'plan')
    # ### end Alembic commands ###
