"""add vertical column to cases

Revision ID: 73da6bd189ef
Revises: b4cc20c90852
Create Date: 2026-07-24 15:51:11.620541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73da6bd189ef'
down_revision: Union[str, None] = 'b4cc20c90852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('vertical', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'vertical')
    # ### end Alembic commands ###
