"""add case escalation category

Revision ID: 81988b4a0025
Revises: 9b595adaa588
Create Date: 2026-07-24 20:28:58.319128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81988b4a0025'
down_revision: Union[str, None] = '9b595adaa588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ESCALATION_CATEGORY_VALUES = (
    'floor_violation', 'info_leak', 'fabrication', 'unconditional_concession',
    'tactic_mismatch', 'premature_acceptance', 'phone_request',
    'escalation_signal_other', 'decision_conflict', 'other',
)


def upgrade() -> None:
    # op.add_column() does NOT auto-create the enum type (unlike
    # op.create_table()) — create it explicitly first.
    sa.Enum(*_ESCALATION_CATEGORY_VALUES, name='escalation_category_enum').create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('escalation_category', sa.Enum(*_ESCALATION_CATEGORY_VALUES, name='escalation_category_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'escalation_category')
    # ### end Alembic commands ###

    sa.Enum(name='escalation_category_enum').drop(op.get_bind(), checkfirst=True)
