"""add case is_demo column

Revision ID: 8d00febe45d4
Revises: bb656f5dd3ea
Create Date: 2026-07-24 17:55:01.561884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d00febe45d4'
down_revision: Union[str, None] = 'bb656f5dd3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cases',
        sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'is_demo')
    # ### end Alembic commands ###
