"""add web channel, user email and session token

Revision ID: 928f2e662de2
Revises: 8d00febe45d4
Create Date: 2026-07-24 18:14:08.654525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928f2e662de2'
down_revision: Union[str, None] = '8d00febe45d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres allows ADD VALUE inside a transaction (PG 12+) as long as the
    # new value isn't used later in the *same* transaction — it isn't here.
    op.execute("ALTER TYPE channel_enum ADD VALUE IF NOT EXISTS 'web'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('web_session_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_web_session_token'), 'users', ['web_session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_web_session_token'), table_name='users')
    op.drop_column('users', 'web_session_token')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###

    # Postgres has no ALTER TYPE ... DROP VALUE, so 'web' stays in
    # channel_enum after downgrade — harmless (nothing references it once
    # this migration's columns are gone), but not a byte-for-byte revert.
