"""add escalation context and llm call dataset columns

Revision ID: 9bae9e6ca971
Revises: 928f2e662de2
Create Date: 2026-07-24 18:57:43.221206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bae9e6ca971'
down_revision: Union[str, None] = '928f2e662de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('escalation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llm_calls', sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llm_calls', sa.Column('response_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_calls', 'response_text')
    op.drop_column('llm_calls', 'request_payload')
    op.drop_column('cases', 'escalation_context')
    # ### end Alembic commands ###
