"""add opt_ins, case counterparty email

Revision ID: 9f33ca821a01
Revises: eb0ab88b4938
Create Date: 2026-07-24 20:04:46.424335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9f33ca821a01'
down_revision: Union[str, None] = 'eb0ab88b4938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opt_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=False),
    # channel_enum already exists (cases/messages/outbound_queue) — reusing it
    # here must NOT re-attempt CREATE TYPE.
    sa.Column('channel', postgresql.ENUM('whatsapp', 'email', 'web', name='channel_enum', create_type=False), nullable=False),
    sa.Column('method', sa.Enum('whatsapp_first_message', 'email_link_click', 'manual_operator', name='opt_in_method_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('counterparty_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'counterparty_email')
    op.drop_table('opt_ins')
    # ### end Alembic commands ###

    sa.Enum(name='opt_in_method_enum').drop(op.get_bind(), checkfirst=True)
