"""initial schema: cases, messages, offers

Revision ID: b4cc20c90852
Revises: 
Create Date: 2026-07-24 15:37:51.095953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4cc20c90852'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Enum('whatsapp', 'email', name='channel_enum'), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_contact', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('discovery', 'anchoring', 'counter', 'concession', 'close', name='state_enum'), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_acceptable_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_external_id'), 'cases', ['external_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', name='channel_enum'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='direction_enum'), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.Enum('us', 'counterparty', name='actor_enum'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('messages')
    op.drop_index(op.f('ix_cases_external_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for postgres ENUMs; drop them
    # explicitly so upgrade() can be re-run cleanly after a downgrade.
    sa.Enum(name='actor_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='direction_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='state_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='channel_enum').drop(op.get_bind(), checkfirst=True)
