"""add users, user_memory, intake fields to messages and llm_calls, outbound audience

Revision ID: bb656f5dd3ea
Revises: 03f18f5deb9e
Create Date: 2026-07-24 17:01:25.301510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb656f5dd3ea'
down_revision: Union[str, None] = '03f18f5deb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Explicitly create the new enum types: unlike op.create_table(),
    # op.add_column() does not auto-issue CREATE TYPE for a new sa.Enum.
    message_kind_enum = sa.Enum('intake', 'negotiation', name='message_kind_enum')
    message_kind_enum.create(op.get_bind(), checkfirst=True)
    audience_enum = sa.Enum('counterparty', 'client', name='audience_enum')
    audience_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('intake_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('user_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_memory_user_key')
    )
    op.add_column('cases', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_cases_user_id_users', 'cases', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('llm_calls', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('llm_calls', 'case_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_llm_calls_user_id_users', 'llm_calls', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column(
        'messages',
        sa.Column(
            'kind',
            sa.Enum('intake', 'negotiation', name='message_kind_enum'),
            nullable=False,
            server_default='negotiation',
        ),
    )
    op.alter_column('messages', 'case_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_messages_user_id_users', 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column(
        'outbound_queue',
        sa.Column(
            'audience',
            sa.Enum('counterparty', 'client', name='audience_enum'),
            nullable=False,
            server_default='counterparty',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_queue', 'audience')
    op.drop_constraint('fk_messages_user_id_users', 'messages', type_='foreignkey')
    op.alter_column('messages', 'case_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'kind')
    op.drop_column('messages', 'user_id')
    op.drop_constraint('fk_llm_calls_user_id_users', 'llm_calls', type_='foreignkey')
    op.alter_column('llm_calls', 'case_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('llm_calls', 'user_id')
    op.drop_constraint('fk_cases_user_id_users', 'cases', type_='foreignkey')
    op.drop_column('cases', 'user_id')
    op.drop_table('user_memory')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit DROP TYPE for the enums it created above.
    sa.Enum(name='audience_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='message_kind_enum').drop(op.get_bind(), checkfirst=True)
